### ISSUE TITLE
PyFMI 2.5 Python3.7 encoding issues

### ISSUE THREAD

**Issue by jschueller** [modelon/PyFMI#10]
When upgrading from PyFMI 2.4 to 2.5 I got encoding issues with my testcases
However it goes fine with Python 2.x, maybe its related to the new locale changes:
https://docs.python.org/3/whatsnew/3.7.html

The first issue is this one:
```
    return pyfmi.load_fmu(path_fmu, kind="CS")
  File "src/pyfmi/fmi.pyx", line 7946, in pyfmi.fmi.load_fmu
  File "src/pyfmi/fmi.pyx", line 6488, in pyfmi.fmi.FMUModelCS2.__init__
  File "src/pyfmi/fmi.pyx", line 3761, in pyfmi.fmi.FMUModelBase2.__init__
  File "src/pyfmi/fmi.pyx", line 45, in pyfmi.fmi.encode
TypeError: latin_1_encode() argument 1 must be str, not bytes
```

**Comment by chria** [comment]
This has been fixed in master and in the 2.5.1 release. Please let me know if it is not resolved.

**Comment by jschueller** [comment]
All is fine, now I get str instead of bytes everywhere, so it's ok.

**Comment by YanfeiNREL** [comment]
I got similar error with Python 3.6.6. But the line number is different. How to fix it?

Traceback (most recent call last):
  File "test_fmi.py", line 5, in <module>
    fmi_bouncing_ball.run_demo()
  File "/home/mindcoder/yes/lib/python3.6/site-packages/pyfmi/examples/fmi_bouncing_ball.py", line 38, in run_demo
    model = load_fmu(fmu_name)
  File "src/pyfmi/fmi.pyx", line 7943, in pyfmi.fmi.load_fmu (src/pyfmi/fmi.c:86531)
  File "src/pyfmi/fmi.pyx", line 7086, in pyfmi.fmi.FMUModelME2.__init__ (src/pyfmi/fmi.c:76471)
  File "src/pyfmi/fmi.pyx", line 3761, in pyfmi.fmi.FMUModelBase2.__init__ (src/pyfmi/fmi.c:40658)
  File "src/pyfmi/fmi.pyx", line 45, in pyfmi.fmi.encode (src/pyfmi/fmi.c:3912)
TypeError: latin_1_encode() argument 1 must be str, not bytes

**Comment by chria** [comment]
This should be fixed in later versions of PyFMI, which version are you using?
