### ISSUE TITLE
Encoding error with Python3

### ISSUE THREAD

**Issue by ChristophGehbauer** [modelon/PyFMI#20]
Hi development team,
We want to use the PyFMI library with Python3, and with some struggle, we got it to compile. However, when loading an FMU we get the following error (see below).
Please can you have a look. 
Thank you very much,
Christoph

```
Traceback (most recent call last):
  File "test_pyfmi.py", line 4, in <module>
    model = load_fmu(path_fmu)
  File "src/pyfmi/fmi.pyx", line 7941, in pyfmi.fmi.load_fmu (src/pyfmi/fmi.c:86469)
  File "src/pyfmi/fmi.pyx", line 6488, in pyfmi.fmi.FMUModelCS2.__init__ (src/pyfmi/fmi.c:71348)
  File "src/pyfmi/fmi.pyx", line 3761, in pyfmi.fmi.FMUModelBase2.__init__ (src/pyfmi/fmi.c:40658)
  File "src/pyfmi/fmi.pyx", line 45, in pyfmi.fmi.encode (src/pyfmi/fmi.c:3912)
TypeError: latin_1_encode() argument 1 must be str, not bytes
```

Here's an example code (Note that the FMU is a CS FMU):

```
from pyfmi import load_fmu
path_fmu = 'bouncingBall.fmu'
model = load_fmu(path_fmu)
```

**Comment by chria** [comment]
Hi, which version of PyFMI are you using? I've seen this issue before and it should have been fixed in the latest release.

**Comment by ChristophGehbauer** [comment]
We've used the latest source version pypi (https://pypi.org/project/PyFMI/#files) which is named PyFMI-2.5.tar.gz.
We tried it with the latest pull from this repo and everything works now. Thank you for your help!
Christoph
