### ISSUE TITLE
Can't install this due to jmodelica.org is down.

### ISSUE THREAD

**Issue by jbkoh** [modelon/PyFMI#4]
Hi,

I would like to run this one but cannot because https://jmodelica.org/FMILibrary is not accessible now. Shouldn't this PyFMI package be supposed to include FMILibrary internally?

If I run ``pip install PYFMI``, I get 
```
Collecting PyFMI
  Using cached https://files.pythonhosted.org/packages/cc/e5/cf5ecd0a6dcf1b1fff89e7a14de6b3d7888a35b8a2e4db22ddb3a9f9b081/PyFMI-2.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f9wyxe_c/PyFMI/setup.py", line 172, in <module>
        raise Exception("FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.")
    Exception: FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.
```

Thanks!

**Comment by chria** [comment]
Hi,

FMIL should be available on JModelica.org now, please try again.

Best
/Christian

**Comment by jbkoh** [comment]
@chria 

Thanks for the quick update! I succeeded in installing the package. But I still have a problem in running it.

When I run ``import pyfmi``, I receive ``ModuleNotFoundError: No module named 'assimulo.solvers.sundials'``. I installed both Assimulo and PyFMI and ran it under Python 3.
Do you have any clue for this?

Furthermore, where can I find API documentation and examples of this PyFMI?

Thanks!

**Comment by jbkoh** [comment]
Thanks for the pointer. I think users like me would've assumed that ``pip install Assimulo`` installs everything Assimulo needs... But I will try to install it separately as you mentioned. Thanks!

**Comment by Amuntaseer** [comment]
Hello, I am facing the same problem of importing the PyFMI library by using the code `pip install PyFMI`. I followed the above solution but still it is not working and showing the same error. Now did you solved the problem ? Can you give me some suggestions @jbkoh

**Comment by jbkoh** [comment]
Hi @Amuntaseer,

I didn't try further after failing at the above error and switched to https://github.com/CATIA-Systems/FMPy.

**Comment by chria** [comment]
Hi,

I'm sorry to hear that you switched to use another tool instead. PyFMI and Assimulo do not work using pip due to additional dependencies that are needed for the packages. To help users with the installation we provide pre-built exe installers for Windows available at https://pypi.org/project/PyFMI/ (and https://pypi.org/project/Assimulo/). We also provide easy installations of the packages through the conda package manager (see https://anaconda.org/chria/pyfmi and https://anaconda.org/chria/assimulo )
